ALTER TABLE SOLICITUD DROP FOREIGN KEY FK_SOLICITUD_ACTIVIDAD_IDACTIVIDAD
ALTER TABLE SOLICITUD DROP FOREIGN KEY FK_SOLICITUD_USUARIO_DNI
ALTER TABLE VALORACION DROP FOREIGN KEY FK_VALORACION_USUARIO_DNI
ALTER TABLE VALORACION DROP FOREIGN KEY FK_VALORACION_ACTIVIDAD_IDACTIVIDAD
ALTER TABLE ACTIVIDAD DROP FOREIGN KEY FK_ACTIVIDAD_PROYECTO_IDPROYECTO
ALTER TABLE NOTIFICACION DROP FOREIGN KEY FK_NOTIFICACION_USUARIO_DNI
ALTER TABLE PROYECTO DROP FOREIGN KEY FK_PROYECTO_ORGANIZACION_DNI
ALTER TABLE MATRICULACION DROP FOREIGN KEY FK_MATRICULACION_TITULACION_IDTITULACION
ALTER TABLE MATRICULACION DROP FOREIGN KEY FK_MATRICULACION_USUARIO_DNI
ALTER TABLE EVALUACION DROP FOREIGN KEY FK_EVALUACION_ALUMNO_EVALUADO_DNI
ALTER TABLE EVALUACION DROP FOREIGN KEY FK_EVALUACION_PROFESOR_EVALUADOR_DNI
ALTER TABLE EVALUACION DROP FOREIGN KEY FK_EVALUACION_ACTIVIDAD_IDACTIVIDAD
ALTER TABLE Coordinar DROP FOREIGN KEY FK_Coordinar_actividad_id
ALTER TABLE Coordinar DROP FOREIGN KEY FK_Coordinar_usuario_id
DROP TABLE USUARIO
DROP TABLE SOLICITUD
DROP TABLE VALORACION
DROP TABLE ACTIVIDAD
DROP TABLE NOTIFICACION
DROP TABLE PROYECTO
DROP TABLE MATRICULACION
DROP TABLE TITULACION
DROP TABLE EVALUACION
DROP TABLE Coordinar
